### ISSUE TITLE
Broken UI on Small Devices with 2 Buttons

### ISSUE THREAD

**Issue by bryandbor** [LouisBarranqueiro/reapop-theme-wybo#6] opened 2017-04-04 16:57 UTC
When a notification should have two buttons the UI is broken on small devices. The second button "wraps" to the next line which is not visible. This means that any notification in which a user should be able to select one of two options instead only sees one option. This make the library unusable on mobile devices when needing to allow users multiple options. Moreover, I use a "Cancel" button so that a user could decide not to do an action, and when the UI breaks in this way, a user cannot even dismiss the notification because "dismissible" has no effect.

![screen shot 2017-04-04 at 9 52 07 am](https://cloud.githubusercontent.com/assets/7401111/24668619/6e28db38-191c-11e7-9636-8c5de1fbbcfb.png)
![screen shot 2017-04-04 at 9 51 35 am](https://cloud.githubusercontent.com/assets/7401111/24668618/6e113262-191c-11e7-9b49-f8fa233df0bf.png)

**Comment by LouisBarranqueiro** [comment] 2017-04-05 05:55
Hey @bryandbor, could you add more information about your mobile (OS & browser with versions) because it works for me.

**Comment by AllanSV** [comment] 2017-06-30 08:32
Hello @LouisBarranqueiro,

I have the same issue. It happens when the screen width is smaller or equal than 371 pixels.
I reproduce the problem on Chrome 59 and Firefox 54.

In real life, this problem happens on mobile devices: their screen is often lower than 371px. See column `CSS width` on <https://mydevice.io/devices/>

**Comment by LouisBarranqueiro** [comment] 2018-02-28 21:38
👋 @AllanSV, Could you please give a the new version? It should be fixed.

**Closed as completed** 2018-03-08 08:19 UTC
